# -*- coding: utf-8 -*-
"""Titanic_servival_classification_in _Logistic_regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11hLMJmkXpSEJo1p0WNQ1mU8ItQEWsVzj
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data=pd.read_csv("/content/drive/MyDrive/titanic.csv")
data.head()

from google.colab import drive
drive.mount('/content/drive')

data=data.drop('Cabin', axis=1)

data.isnull().sum()

data["Age"].fillna(data['Age'].median(),inplace=True)
data["Embarked"].fillna(data['Embarked'].mode()[0],inplace=True)

data.isnull().sum()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data["Sex"]=le.fit_transform(data["Sex"])
data["Embarked"]=le.fit_transform(data["Embarked"])
data["Ticket"]=le.fit_transform(data["Ticket"])
data["Fare"]=le.fit_transform(data["Fare"])
data["Name"]=le.fit_transform(data["Name"])

data

from sklearn.model_selection import train_test_split
x=data.drop(["Survived"],axis=1)
y=data['Survived']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=120)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

y_pred=lr.predict(x_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

#for big
#Save model
'''import joblib
joblib.dump(lr,'model.pkl')'''

import pickle
#Save model
with open('Titanic_servival_classification_in_Logistic_regression.pkl','wb') as f:
  pickle.dump(lr,f)

